FleetDeadlines/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace FleetDeadlines.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

FleetDeadlines/Pages/Fleet.cshtml.cs
using FleetDeadlines.Data;
using FleetDeadlines.Models;
using FleetDeadlines.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FleetDeadlines.Pages
{
    public class FleetModel : PageModel
    {
        private readonly FleetDeadlines.Data.LocalDbContext _context;

        public FleetModel(LocalDbContext context)
        {
            _context = context;
        }

        [BindProperty(SupportsGet = true)]
        public string? _NewRVN { get; set; }

        public Vehicle NewVehicle;

        public IList<Vehicle> Vehicles { get; set; } = default!;


        public async Task OnGetAsync()
        {
            if (_context.Vehicles != null)
            {
                Vehicles = (IList<Vehicle>)await _context.Vehicles.ToListAsync();
            }

            if (!string.IsNullOrEmpty(_NewRVN))
            {
                NewVehicle = DvlaGet.withReg(_NewRVN);
                Console.WriteLine(NewVehicle.Make);
            }
        }

        public async Task<IActionResult> OnPostRVNLookupAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _NewRVN = Request.Form["NewRVN"];
            //NewVehicle = DvlaGet.withReg(_NewRVN);
            //Console.WriteLine(NewVehicle.Make);

            return Page();
            //return RedirectToPage();
        }

        //public async Task<IActionResult> OnPostAsync()
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return Page();
        //    }

        //    //_context.Movie.Add(Movie);
        //    //await _context.SaveChangesAsync();

        //    return RedirectToPage();
        //}
    }
}

FleetDeadlines/Pages/Fleet/Change.cshtml.cs
using FleetDeadlines.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FleetDeadlines.Pages.Fleet
{
    public class ChangeModel : PageModel
    {
        private readonly Data.LocalDbContext _context;

        public ChangeModel(Data.LocalDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Vehicle ThisVehicle { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles.FirstOrDefaultAsync(m => m.RegistrationNumber == id);

            if (vehicle == null)
            {
                return NotFound();
            }
            else
            {
                ThisVehicle = vehicle;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ThisVehicle).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!VehicleExists(ThisVehicle.RegistrationNumber))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool VehicleExists(string id)
        {
            return (_context.Vehicles?.Any(e => e.RegistrationNumber == id)).GetValueOrDefault();
        }
    }
}

FleetDeadlines/Pages/Fleet/Delete.cshtml.cs
using FleetDeadlines.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FleetDeadlines.Pages.Fleet
{
    public class DeleteModel : PageModel
    {
        private readonly Data.LocalDbContext _context;

        public DeleteModel(Data.LocalDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Vehicle ThisVehicle { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles.FirstOrDefaultAsync(m => m.RegistrationNumber == id);

            if (vehicle == null)
            {
                return NotFound();
            }
            else
            {
                ThisVehicle = vehicle;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }
            var vehicle = await _context.Vehicles.FindAsync(id);

            if (vehicle != null)
            {
                ThisVehicle = vehicle;
                _context.Vehicles.Remove(ThisVehicle);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

FleetDeadlines/Pages/Fleet/Find.cshtml.cs
using FleetDeadlines.Models;
using FleetDeadlines.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FleetDeadlines.Pages.Fleet
{
    public class FindModel : PageModel
    {
        private readonly Data.LocalDbContext _context;
        private readonly IConfiguration _configuration;

        public FindModel(Data.LocalDbContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        [BindProperty]
        public Vehicle ThisVehicle { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = DvlaGet.withReg(id, _configuration["UserOptions:RealApi"], _configuration["UserOptions:RealKey"]);

            if (vehicle == null)
            {
                return NotFound();
            }
            else
            {
                ThisVehicle = vehicle;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string? id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var vehicle = await _context.Vehicles.FirstOrDefaultAsync(m => m.RegistrationNumber == id);
            if (vehicle != null)
            {
                // Always override with information from DVLA api
                _context.Attach(ThisVehicle).State = EntityState.Modified;
            }
            else
            {
                // The extra call to the DVLA API should not be necessary here
                // But without it, ThisVehicle seems to clear its contents as the page is navigating away - except for RegistrationNumber, oddly enough
                // TODO: More investigation needed
                _context.Vehicles.Add(DvlaGet.withReg(ThisVehicle.RegistrationNumber, _configuration["UserOptions:RealApi"], _configuration["UserOptions:RealKey"]));
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

FleetDeadlines/Pages/Fleet/Index.cshtml.cs
using FleetDeadlines.Data;
using FleetDeadlines.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FleetDeadlines.Pages.Fleet
{
    public class IndexModel : PageModel
    {
        private readonly LocalDbContext _context;

        public IndexModel(LocalDbContext context)
        {
            _context = context;
        }

        [BindProperty(SupportsGet = true)]
        public string? NewRVN { get; set; }

        public Vehicle NewVehicle;

        public IList<Vehicle> Vehicles { get; set; } = default!;


        public async Task OnGetAsync()
        {
            if (_context.Vehicles != null)
            {
                Vehicles = await _context.Vehicles.ToListAsync();
            }
        }
    }
}

FleetDeadlines/Pages/Index.cshtml.cs
using FleetDeadlines.Data;
using FleetDeadlines.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FleetDeadlines.Pages
{
    public class IndexModel : PageModel
    {
        private readonly FleetDeadlines.Data.LocalDbContext _context;

        public IndexModel(LocalDbContext context)
        {
            _context = context;
        }

        public IList<Vehicle> Vehicles { get; set; } = default!;
        public IList<Vehicle> ValidVehicles { get; set; } = default!;
        
        public IList<Vehicle> ProblemVehicles { get; set; } = default!;


        public string DaysCalculations(Vehicle v)
        {
            DateTime motDate = DateTime.Parse(v.MotExpiryDate);
            DateTime taxDate = DateTime.Parse(v.TaxDueDate);

            if (motDate == taxDate)
            {
                return StylingInject(motDate, $"{DaysRemaining(motDate)} days remaining for both MOT and Tax");
            } 
            else if (motDate < taxDate)
            {
                return StylingInject(motDate, $"{DaysRemaining(motDate)} days remaining for MOT <br />{DaysRemaining(taxDate)} days remaining for Tax");
            } 
            else
            {
                return StylingInject(taxDate, $"{DaysRemaining(taxDate)} days remaining for Tax <br />{DaysRemaining(motDate)} days remaining for MOT");
            }
        }

        private int DaysRemaining(DateTime d)
        {
            TimeSpan timeSpan = d - DateTime.Now;
            return (int)timeSpan.TotalDays;
        }

        // Add coloration to upcomind deadlines text. 
        // Hacky and should be done in a better way, but it'll do for now
        private string StylingInject(DateTime deadline, string target)
        {
            // Past deadline(s)!
            if (DaysRemaining(deadline) < 0)
            {
                return $"<div style=\"color:red;\">{target}</div>";
            }
            
            // Closest deadline within two weeks
            if (DaysRemaining(deadline) < 14)
            {
                return $"<div style=\"color:blue;\">{target}</div>";
            }
            
            return target;
        }

        public async Task OnGetAsync()
        {
            if (_context.Vehicles != null)
            {
                Vehicles = (IList<Vehicle>)await _context.Vehicles.ToListAsync();

                Func<Vehicle, bool> validPredicate = obj => (obj.MotExpiryDate != null && obj.TaxDueDate != null) == true;

                ValidVehicles = Vehicles.Where(validPredicate).OrderBy(item => Math.Min(DateTime.Parse(item.MotExpiryDate).Ticks, DateTime.Parse(item.TaxDueDate).Ticks)).ToList();

                ProblemVehicles = Vehicles.Where(item => !validPredicate(item)).ToList();
            }
        }
    }
}

FleetDeadlines/Pages/Fleet.cshtml
@page
@model FleetDeadlines.Pages.FleetModel
@{
    ViewData["Title"] = "Manage Fleet";
}


<div class="text-center">
    <h1 class="display-4">Fleet</h1>

    <form method="post" asp-page-handler="RVNLookup" class="row p-4 row-cols-sm-auto g-2 bg-light mt-4 align-items-center">
        <div class="col-1 w-25">
            <label for="NewRVN">
                <strong>
                    Add new Vehicle: 
                </strong>
            </label>
        </div>
        <div class="col-2 w-50">
            <input type="text" name="NewRVN" id="NewRVN" class="form-control" placeholder="Enter VRN without any spaces" />
        </div>
        <div class="col-3 w-25">
            <button type="submit" class="btn btn-primary">
                <strong>
                    Find and Add
                </strong>
            </button>
        </div>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Vehicles[0].RegistrationNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vehicles[0].Make)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vehicles[0].Colour)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vehicles[0].YearOfManufacture)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Vehicles)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.RegistrationNumber)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Make)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Colour)
                </td>
                <td>
                    @Html.DisplayFor(model => item.YearOfManufacture)
                </td>
                <td>
                    <a asp-page="./Details" asp-route-id="@item.RegistrationNumber">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.RegistrationNumber">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

FleetDeadlines/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Fleet Deadlines";
}

<br>
<div class="text-center">
    <h1 class="display-4">Upcoming Deadlines</h1>
</div>

@if (Model.ValidVehicles != null && Model.ValidVehicles.Count != 0)
{
    <br>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].RegistrationNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].Make)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].Colour)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].YearOfManufacture)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].MotStatus)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].MotExpiryDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].TaxDueDate)
                </th>
                <th>
                    DEADLINES
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ValidVehicles)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => item.RegistrationNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Make)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Colour)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.YearOfManufacture)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.MotStatus)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.MotExpiryDate)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.TaxDueDate)
                    </td>
                    <td>
                        @Html.Raw(Model.DaysCalculations(item))
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="text-center">
        <br>
        <br>
        <p>
            You have 0 cars in your fleet in good standing with the DVLA.
        </p>
    </div>
}

@if (Model.ProblemVehicles != null && Model.ProblemVehicles.Count != 0)
{
    <br>
    <br>
    <div class="text-center">
        <h2 class="display-4">Other Problems</h2>
        <p>
            Please contact DVLA directly to resolve these issues.
        </p>
    </div>

    <br>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].RegistrationNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].Make)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].Colour)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].YearOfManufacture)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].MotStatus)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].MotExpiryDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicles[0].TaxDueDate)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ProblemVehicles)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => item.RegistrationNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Make)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Colour)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.YearOfManufacture)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.MotStatus)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.MotExpiryDate)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.TaxDueDate)
                    </td>
                </tr>
            }
        </tbody>
    </table>
}